In [46]:
import pandas as pd

In [61]:
glacier_length = pd.read_csv("data\lengthchange.csv", sep = ";", header= 4)
glacier_length.head()

,glacier name,glacier id,start date of observation,quality of start date,end date of observation,quality of end date,length change,elevation of glacier tongue,observer
0,NaN,(according to Swiss Glacier Inventory),date_start,x = date not exactly known,date_end,x = date not exactly known,dL,h_min,NaN
1,NaN,NaN,yyyy-mm-dd (ISO 8601),NaN,yyyy-mm-dd (ISO 8601),NaN,m,m asl.,NaN
2,Silvrettagletscher,A10g-05,1956-09-01,x,1957-09-01,x,-8.00,None,-
3,Silvrettagletscher,A10g-05,1957-09-01,x,1958-09-01,x,-9.00,None,-
4,Silvrettagletscher,A10g-05,1958-09-01,x,1959-09-01,x,-16.00,None,-

In [25]:
glacier_massbalance = pd.read_csv("data\massbalance_observation.csv", sep = ";", header= 4)
glacier_massbalance.head()

,glacier name,glacier id,start date of observation,end date of winter observation,end date of observation,winter mass balance,summer mass balance,annual mass balance,equilibrium line altitude,accumulation area ratio,glacier area,minimum elevation of glacier,maximum elevation of glacier,observer
0,NaN,(according to Swiss Glacier Inventory),date_start,date_end_winter,date_end,Bw,Bs,Ba,ELA,AAR,area,h_min,h_max,NaN
1,NaN,NaN,yyyy-mm-dd (ISO 8601),yyyy-mm-dd (ISO 8601),yyyy-mm-dd (ISO 8601),mm w.e.,mm w.e.,mm w.e.,m asl.,%,km2,m asl.,m asl.,NaN
2,Silvrettagletscher,A10g-05,1914-10-01,1915-04-30,1915-09-30,1445,-1860,-415,2795,45,4.06687,2406,3185,"VAW / ETH Zuerich, Huss et al 2015, Journal ..."
3,Silvrettagletscher,A10g-05,1915-09-29,1916-05-15,1916-08-05,1519,-683,836,2525,93,3.55563,2414,3091,"VAW / ETH Zuerich, Huss et al 2015, Journal ..."
4,Silvrettagletscher,A10g-05,1916-08-05,1917-03-11,1917-09-07,1878,-1603,275,2685,69,3.55563,2414,3091,"VAW / ETH Zuerich, Huss et al 2015, Journal ..."

In [62]:
glacier_volumechange = pd.read_csv("data\Volumechange.csv", sep = ";", header = 4)
glacier_volumechange.head()

,glacier name,glacier id,start date of observation,quality of start date,end date of observation,quality of start date.1,glacier area at start date,glacier area at end date,volume change,mean thickness change,annual geodetic mass balance,observer
0,NaN,(according to Swiss Glacier Inventory),date_start,x = date not exactly known,date_end,x = date not exactly known,area_start,area_end,dV,dh_mean,Bgeod,NaN
1,NaN,NaN,yyyy-mm-dd (ISO 8601),NaN,yyyy-mm-dd (ISO 8601),NaN,km2,km2,km3,m,m w.e. a-1,NaN
2,Silvrettagletscher,A10g-05,1938-09-01,x,1959-08-31,NaN,3.557312,3.227714,-0.028666,-8.00,-0.34,-
3,Silvrettagletscher,A10g-05,1959-08-31,NaN,1973-09-12,NaN,3.227714,3.146731,-0.004822,-1.48,-0.09,-
4,Silvrettagletscher,A10g-05,1973-09-12,NaN,1986-09-29,NaN,3.146731,3.138600,0.009488,2.97,0.20,-